apiVersion: v1
kind: Pod
metadata:
  name: pod-secret
spec:
  containers:
  - name: nginx
    image: nginx
    imagePullPolicy: IfNotPresent
    env:
    - name: SECRET_USUARIO
      valueFrom:
        secretKeyRef:
          name: misecret2
          key: usuario
    - name: SECRET_CLAVE
      valueFrom:
        secretKeyRef:
          name: misecret2
          key: clave
